### ISSUE TITLE
Delete account data after failed attempt to retrieve certificates

### ISSUE THREAD

**Issue by n3o77** [zhangjiayin/caddy-mysql-storage#3]
When caddy fails to get certificates i get the following error after reload:

```
logger=tls.obtain msg=could not get certificate from issuer identifier=#my_domain# issuer=acme-v02.api.letsencrypt.org-directory error=HTTP 400 urn:ietf:params:acme:error:invalidContact - Error creating new account :: "default.json" is not a valid e-mail address
logger=tls.obtain msg=will retry error=[#my_domain#] Obtain: registering account [mailto:default.json] with server: attempt 1: https://acme-v02.api.letsencrypt.org/acme/new-acct: HTTP 400 urn:ietf:params:acme:error:invalidContact - Error creating new account :: "default.json" is not a valid e-mail address attempt=1 retrying_in=60 elapsed=0.566465028 max_duration=2592000
```

I then truncate the 2 certmagic_* tables, restart and everything works fine (if my domain config is right). I don't have the issue without using this storage solution and if i understand the logs correctly that's because the storage is then cleaned up automatically. Truncating the tables is also not a great solution as all other received certs would need to be renewed as well.

**Comment by zhangjiayin** [comment]
Thank you for bringing this issue to my attention. I understand the problem you're encountering and would like to help resolve it. However, I recommend checking the official implementation at [filestorage.go in the certmagic repository](https://github.com/caddyserver/certmagic/blob/master/filestorage.go), as it doesn't include logic to validate the validity of the stored []byte. Given this, I currently do not believe the issue is specific to this storage module. Please consider checking other potential issues or testing with alternative storage methods to further diagnose the problem. I look forward to hearing the results of your further testing.

**Comment by n3o77** [comment]
Thanks for getting back to me. I broke it down to the 2 entries in the database but had no time to dig deeper. I'll try to so in the coming days.

**Comment by zhangjiayin** [comment]
if any news  reopen it , please.
